import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import {
  Sparkles,
  TrendingUp,
  AlertOctagon,
  Brain,
  ChevronDown,
} from "lucide-react";
import { AppShell } from "@/components/AppShell";
import {
  BarChart,
  Bar,
  ResponsiveContainer,
  XAxis,
  YAxis,
  Tooltip,
  Cell,
} from "recharts";
import { getInsights, type Insight } from "@/lib/api";

export const Route = createFileRoute("/app/insights")({
  head: () => ({ meta: [{ title: "AI Insights · TrustGuard AI" }] }),
  component: Insights,
});

const insights = [
  {
    id: "1",
    severity: "high",
    title: "SIM swap fraud cluster detected in Chittagong",
    summary: "12 SIM swap events tied to 4 mule accounts in the last 6 hours.",
    detail:
      "Our AI engine correlated SIM swap timestamps with new device registrations and outbound transfers exceeding R40,000. The pattern matches a known mule-network signature observed in Q3 2025. Recommend freezing the linked accounts and notifying the telecom partner via the CAMARA SIM Swap webhook.",
    factors: [
      "SIM Swap velocity",
      "New device",
      "High-value withdrawals",
      "Geo-cluster",
    ],
  },
  {
    id: "2",
    severity: "medium",
    title: "Step-up friction increasing for legitimate users",
    summary: "Approve-after-stepup rate dropped 6% week-over-week.",
    detail:
      "Users on Robi network are facing more KYC challenges due to a name normalization mismatch. Suggest tuning the KYC fuzzy-match threshold from 0.82 → 0.78 for that operator segment.",
    factors: ["Operator: Robi", "KYC fuzzy match", "Drop-off rate"],
  },
  {
    id: "3",
    severity: "low",
    title: "Device fingerprint coverage at 94.2%",
    summary: "5.8% of sessions lack a stable device identifier.",
    detail:
      "Mostly observed on jailbroken Android devices. Consider falling back to TLS-fingerprint + behavioral biometrics for these sessions.",
    factors: ["Device fingerprint", "Android", "Coverage"],
  },
];

const factorImpact = [
  { factor: "SIM Swap", impact: 78 },
  { factor: "New Device", impact: 64 },
  { factor: "KYC Mismatch", impact: 52 },
  { factor: "Geo Anomaly", impact: 38 },
  { factor: "Velocity", impact: 31 },
  { factor: "Number Unverif.", impact: 22 },
];

function Insights() {
  const [open, setOpen] = useState<string | null>("1");
  const [items, setItems] = useState<Insight[]>(insights);

  useEffect(() => {
    getInsights()
      .then((backendInsights) => {
        setItems(
          backendInsights.map((insight) => ({
            ...insight,
            detail:
              insight.detail ??
              insights.find((fallback) => fallback.id === insight.id)?.detail ??
              insight.summary,
          })),
        );
      })
      .catch((error) => {
        console.warn(
          "Backend insights fetch failed, using local fallback.",
          error,
        );
      });
  }, []);

  return (
    <AppShell
      title="AI Insights"
      subtitle="Patterns, anomalies and recommended actions, generated by the trust engine"
    >
      <div className="grid lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-4">
          <div className="rounded-2xl bg-gradient-primary p-6 text-primary-foreground shadow-elegant relative overflow-hidden">
            <Brain
              className="absolute -right-6 -bottom-6 w-32 h-32 opacity-10"
              strokeWidth={1}
            />
            <div className="flex items-center gap-2 text-xs uppercase tracking-widest opacity-80 mb-2">
              <Sparkles className="w-3.5 h-3.5" /> Daily AI summary
            </div>
            <h2 className="text-2xl font-display font-semibold leading-snug max-w-2xl">
              "Fraud pressure is up 18% — concentrated SIM swap activity in
              Chittagong is driving most of today's blocks. Three mule clusters
              identified."
            </h2>
            <div className="mt-5 flex items-center gap-3 text-xs opacity-80">
              <span>Generated 2 min ago</span>
              <span>·</span>
              <span>Model: TrustGuard-AI v0.4</span>
            </div>
          </div>

          {items.map((ins) => {
            const isOpen = open === ins.id;
            const sevColor =
              ins.severity === "high"
                ? "var(--destructive)"
                : ins.severity === "medium"
                  ? "var(--warning)"
                  : "var(--success)";
            return (
              <motion.div
                key={ins.id}
                layout
                className="rounded-2xl bg-card border border-border shadow-card overflow-hidden"
              >
                <button
                  onClick={() => setOpen(isOpen ? null : ins.id)}
                  className="w-full text-left p-5 flex items-center gap-4 hover:bg-muted/50 transition-base"
                >
                  <div
                    className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
                    style={{ background: `${sevColor}15`, color: sevColor }}
                  >
                    <AlertOctagon className="w-5 h-5" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span
                        className="text-[10px] uppercase tracking-widest font-semibold"
                        style={{ color: sevColor }}
                      >
                        {ins.severity}
                      </span>
                    </div>
                    <h3 className="font-semibold mt-0.5">{ins.title}</h3>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      {ins.summary}
                    </p>
                  </div>
                  <ChevronDown
                    className={`w-4 h-4 text-muted-foreground transition-base ${isOpen ? "rotate-180" : ""}`}
                  />
                </button>
                {isOpen && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    className="px-5 pb-5"
                  >
                    <div className="pl-14">
                      <p className="text-sm leading-relaxed text-muted-foreground">
                        {ins.detail}
                      </p>
                      <div className="mt-4 flex flex-wrap gap-1.5">
                        {ins.factors.map((f) => (
                          <span
                            key={f}
                            className="px-2.5 py-1 rounded-full bg-muted text-[11px] font-medium"
                          >
                            {f}
                          </span>
                        ))}
                      </div>
                    </div>
                  </motion.div>
                )}
              </motion.div>
            );
          })}
        </div>

        <div className="space-y-4">
          <div className="rounded-2xl bg-card border border-border shadow-card p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-display font-semibold">Top risk factors</h3>
              <TrendingUp className="w-4 h-4 text-primary" />
            </div>
            <div className="h-64">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart
                  data={factorImpact}
                  layout="vertical"
                  margin={{ left: 0 }}
                >
                  <XAxis type="number" hide />
                  <YAxis
                    type="category"
                    dataKey="factor"
                    axisLine={false}
                    tickLine={false}
                    tick={{ fontSize: 11, fill: "var(--muted-foreground)" }}
                    width={90}
                  />
                  <Tooltip
                    cursor={{ fill: "var(--muted)" }}
                    contentStyle={{
                      borderRadius: 12,
                      border: "1px solid var(--border)",
                      background: "var(--card)",
                      fontSize: 12,
                    }}
                  />
                  <Bar dataKey="impact" radius={[0, 8, 8, 0]}>
                    {factorImpact.map((d, i) => (
                      <Cell
                        key={i}
                        fill={
                          d.impact > 60
                            ? "var(--destructive)"
                            : d.impact > 40
                              ? "var(--warning)"
                              : "var(--primary)"
                        }
                      />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="rounded-2xl bg-card border border-border shadow-card p-6">
            <h3 className="font-display font-semibold mb-3">Model health</h3>
            <div className="space-y-3">
              {[
                { l: "Precision", v: 0.962 },
                { l: "Recall", v: 0.911 },
                { l: "F1", v: 0.936 },
              ].map((m) => (
                <div key={m.l}>
                  <div className="flex items-center justify-between text-xs mb-1.5">
                    <span className="text-muted-foreground">{m.l}</span>
                    <span className="font-mono font-semibold">
                      {m.v.toFixed(3)}
                    </span>
                  </div>
                  <div className="h-1.5 bg-muted rounded-full overflow-hidden">
                    <motion.div
                      initial={{ width: 0 }}
                      animate={{ width: `${m.v * 100}%` }}
                      transition={{ duration: 1 }}
                      className="h-full bg-gradient-primary rounded-full"
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
