/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AppIndexRouteImport } from "./routes/app.index";
import { Route as AppUsersRouteImport } from "./routes/app.users";
import { Route as AppTimelineRouteImport } from "./routes/app.timeline";
import { Route as AppSimulatorRouteImport } from "./routes/app.simulator";
import { Route as AppInsightsRouteImport } from "./routes/app.insights";
import { Route as AppApiRouteImport } from "./routes/app.api";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/app/",
  path: "/app/",
  getParentRoute: () => rootRouteImport,
} as any);
const AppUsersRoute = AppUsersRouteImport.update({
  id: "/app/users",
  path: "/app/users",
  getParentRoute: () => rootRouteImport,
} as any);
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: "/app/timeline",
  path: "/app/timeline",
  getParentRoute: () => rootRouteImport,
} as any);
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: "/app/simulator",
  path: "/app/simulator",
  getParentRoute: () => rootRouteImport,
} as any);
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: "/app/insights",
  path: "/app/insights",
  getParentRoute: () => rootRouteImport,
} as any);
const AppApiRoute = AppApiRouteImport.update({
  id: "/app/api",
  path: "/app/api",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/app/api": typeof AppApiRoute;
  "/app/insights": typeof AppInsightsRoute;
  "/app/simulator": typeof AppSimulatorRoute;
  "/app/timeline": typeof AppTimelineRoute;
  "/app/users": typeof AppUsersRoute;
  "/app/": typeof AppIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/app/api": typeof AppApiRoute;
  "/app/insights": typeof AppInsightsRoute;
  "/app/simulator": typeof AppSimulatorRoute;
  "/app/timeline": typeof AppTimelineRoute;
  "/app/users": typeof AppUsersRoute;
  "/app": typeof AppIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/app/api": typeof AppApiRoute;
  "/app/insights": typeof AppInsightsRoute;
  "/app/simulator": typeof AppSimulatorRoute;
  "/app/timeline": typeof AppTimelineRoute;
  "/app/users": typeof AppUsersRoute;
  "/app/": typeof AppIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/app/api"
    | "/app/insights"
    | "/app/simulator"
    | "/app/timeline"
    | "/app/users"
    | "/app/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/app/api"
    | "/app/insights"
    | "/app/simulator"
    | "/app/timeline"
    | "/app/users"
    | "/app";
  id:
    | "__root__"
    | "/"
    | "/app/api"
    | "/app/insights"
    | "/app/simulator"
    | "/app/timeline"
    | "/app/users"
    | "/app/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppApiRoute: typeof AppApiRoute;
  AppInsightsRoute: typeof AppInsightsRoute;
  AppSimulatorRoute: typeof AppSimulatorRoute;
  AppTimelineRoute: typeof AppTimelineRoute;
  AppUsersRoute: typeof AppUsersRoute;
  AppIndexRoute: typeof AppIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/": {
      id: "/app/";
      path: "/app";
      fullPath: "/app/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/users": {
      id: "/app/users";
      path: "/app/users";
      fullPath: "/app/users";
      preLoaderRoute: typeof AppUsersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/timeline": {
      id: "/app/timeline";
      path: "/app/timeline";
      fullPath: "/app/timeline";
      preLoaderRoute: typeof AppTimelineRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/simulator": {
      id: "/app/simulator";
      path: "/app/simulator";
      fullPath: "/app/simulator";
      preLoaderRoute: typeof AppSimulatorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/insights": {
      id: "/app/insights";
      path: "/app/insights";
      fullPath: "/app/insights";
      preLoaderRoute: typeof AppInsightsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/api": {
      id: "/app/api";
      path: "/app/api";
      fullPath: "/app/api";
      preLoaderRoute: typeof AppApiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppApiRoute: AppApiRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppSimulatorRoute: AppSimulatorRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
